export const packageGroups = [
  {
    key: 'tint',
    label: 'Window Tint',
    eyebrow: 'Heat, privacy, and UV control',
    visual: '/assets/package-tint-coverage.png',
    alt: 'White sedan diagram showing window tint coverage areas',
    options: [
      {
        key: 'carbon',
        name: 'Carbon Film',
        tag: 'Privacy',
        title: 'A clean factory-style shade for privacy and glare control.',
        coverage: 'carbon',
        visual: '/assets/package-carbon-film-clean.png',
        alt: 'White sedan with carbon window tint installed',
        quote: 'Quote after vehicle review',
        bestFor: 'Clean look, privacy, and budget-conscious tint.',
        includes: ['All side windows', 'Front windshield option', 'Back window', 'Sunroof option'],
        copy:
          'A strong entry point for drivers who want a darker look and a cleaner cabin feel without overcomplicating the build.',
      },
      {
        key: 'ceramic',
        name: 'Ceramic Film',
        tag: 'Comfort',
        title: 'Premium comfort with stronger heat rejection and cleaner clarity.',
        coverage: 'ceramic',
        visual: '/assets/package-ceramic-film-clean.png',
        alt: 'White sedan with ceramic window tint installed',
        quote: 'Quote after vehicle review',
        bestFor: 'Sacramento heat, daily driving, and better cabin comfort.',
        includes: ['All side windows', 'Front windshield option', 'Back window', 'Sunroof option'],
        copy:
          'The balanced choice for Sacramento heat: refined privacy, better interior comfort, UV protection, and a finish that looks intentional.',
      },
      {
        key: 'nano',
        name: 'IR Nano Ceramic',
        tag: 'Elite',
        title: 'Highest-performance tint for maximum comfort and clarity.',
        coverage: 'nano',
        visual: '/assets/package-nano-ceramic-clean.png',
        alt: 'White sedan with nano ceramic window tint installed',
        quote: 'Quote after vehicle review',
        bestFor: 'Premium builds, strong IR rejection, and optical clarity.',
        includes: ['All side windows', 'Front windshield option', 'Back window', 'Sunroof option'],
        copy:
          'Built for customers who want the cleanest optical finish, stronger infrared rejection, and a premium cabin feel every day.',
      },
    ],
  },
  {
    key: 'ppf',
    label: 'PPF Packages',
    eyebrow: 'Rock chip and scratch defense',
    visual: '/assets/ppf-packages/partial-hood.png',
    alt: 'Paint protection film coverage diagram',
    options: [
      {
        key: 'partial-hood',
        name: 'Partial Hood',
        tag: 'Starter',
        title: 'Entry-level impact protection for the front hood area.',
        coverage: 'partial-hood',
        visual: '/assets/ppf-packages/partial-hood.png',
        alt: 'Partial hood paint protection film coverage diagram',
        quote: 'Quote after vehicle review',
        bestFor: 'Light commuter protection and focused hood coverage.',
        includes: ['Partial hood', 'Computer-cut film', 'Clean front-edge protection'],
        copy:
          'A simple way to protect the most visible front edge without building a full front-end package.',
      },
      {
        key: 'full-hood',
        name: 'Full Hood',
        tag: 'Hood',
        title: 'Full hood coverage for a cleaner, more complete front finish.',
        coverage: 'full-hood',
        visual: '/assets/ppf-packages/full-hood.png',
        alt: 'Full hood paint protection film coverage diagram',
        quote: 'Quote after vehicle review',
        bestFor: 'Newer vehicles, dark paint, and cleaner hood protection.',
        includes: ['Full hood', 'Wrapped edge options', 'Finish inspection'],
        copy:
          'A stronger hood-focused package for owners who want fewer visible film lines and better long-term finish protection.',
      },
      {
        key: 'partial-front',
        name: 'Partial Front',
        tag: 'Value',
        title: 'Balanced front-end protection for daily road debris.',
        coverage: 'partial-front',
        visual: '/assets/ppf-packages/partial-front.png',
        alt: 'Partial front paint protection film coverage diagram',
        quote: 'Quote after vehicle review',
        bestFor: 'Daily drivers that need bumper plus partial panel coverage.',
        includes: ['Partial hood', 'Partial fenders', 'Full bumper'],
        copy:
          'A practical package for drivers who want protection where road rash happens most often.',
      },
      {
        key: 'partial-front-mirrors',
        name: 'Partial Front + Mirrors',
        tag: 'Popular',
        title: 'Partial front protection with mirror coverage added.',
        coverage: 'partial-front-mirrors',
        visual: '/assets/ppf-packages/partial-front-mirrors.png',
        alt: 'Partial front with mirrors paint protection film coverage diagram',
        quote: 'Quote after vehicle review',
        bestFor: 'Highway driving, daily use, and exposed mirror caps.',
        includes: ['Partial hood', 'Partial fenders', 'Full bumper', 'Mirrors'],
        copy:
          'A smarter daily-driver package when mirror caps and front bumper take regular highway abuse.',
      },
      {
        key: 'full-front',
        name: 'Full Front',
        tag: 'Best seller',
        title: 'The cleanest front-end package for serious protection.',
        coverage: 'full-front',
        visual: '/assets/ppf-packages/full-front.png',
        alt: 'Full front paint protection film coverage diagram',
        quote: 'Quote after vehicle review',
        bestFor: 'Performance cars, luxury builds, and fresh paint preservation.',
        includes: ['Full hood', 'Full fenders', 'Full bumper', 'Mirrors'],
        copy:
          'The go-to package for owners who want full front-end defense with a premium, intentional finish.',
      },
      {
        key: 'full-vehicle',
        name: 'Full Vehicle',
        tag: 'Flagship',
        title: 'Complete exterior protection for long-term ownership.',
        coverage: 'full-vehicle',
        visual: '/assets/ppf-packages/full-vehicle.png',
        alt: 'Full vehicle paint protection film coverage diagram',
        quote: 'Quote after vehicle review',
        bestFor: 'Black paint, luxury vehicles, exotics, and resale value.',
        includes: ['All painted exterior panels', 'High-impact areas', 'Wrapped edge options'],
        copy:
          'Maximum paint preservation for owners who want the whole vehicle protected, not just the front.',
      },
    ],
  },
];
